export type Member = {
  name: string,
  photo: string,
  role: string,
  contacts: {
    telegram?: string,
    instagram?: string,
    linkedin?: string,
  } | null,
  description: string,
  avatar: string
  avatarHovered: string
}

export const members: Member[] = [
  {
    name: 'Viktoria Ermakova',
    role: 'Community Manager',
    photo: 'vika',
    contacts: {
      linkedin: 'ermakova-viktoria',
      telegram: 'VErmakova',
      instagram: 'vika_ermakova_globe',
    },
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'vika1_ajkmma',
    avatarHovered: 'vika2_mhe1uj',
  },
  {
    name: 'Dmitrii Solomonov',
    role: 'Backend Developer',
    photo: 'dima',
    contacts: null,
    description: 'Keeping the sound crisp and the conversations sharp',
    avatar: 'dima1_qqmlw7',
    avatarHovered: 'dima2_tuuxhn',
  },
  {
    name: 'Leonid Safronov',
    role: 'iOS Developer',
    photo: 'IMG_1176_uodayi',
    contacts: {
      linkedin: 'leosafronov',
      telegram: 'leonidsafronov',
      instagram: 'leonidsafronoff',
    },
    description: 'Joined IT Connect team on the first weekend after arriving in Belgrade',
    avatar: 'leo1_yve4rt',
    avatarHovered: 'leo2_wwdjvk',
  },
  {
    name: 'Yulia Makutu',
    role: 'Backend Developer',
    photo: 'yulia',
    contacts: {
      linkedin: 'makutu888',
      telegram: 'juliyamakutu',
      instagram: 'makutucoach',
    },
    description: 'She doesn’t just raise funds—she raises the energy level too!',
    avatar: 'yulya1_t5ghwr',
    avatarHovered: 'yulya2_jndof8',
  },
  {
    name: 'Anton Klochkov',
    role: 'Digital Marketing Specialist',
    photo: 'anton',
    contacts: {
      linkedin: 'antonyklochkov',
      telegram: 'klochk0v',
      instagram: 'klochk0v',
    },
    description: 'Your code might crash, but his photos are always flawless',
    avatar: 'anton1_nbrt3t',
    avatarHovered: 'anton2_hhf9uc',
  },
  {
    name: 'Elena Solomonova',
    role: 'UX/UI Designer',
    photo: 'lena',
    contacts: null,
    description: 'Making meetups look as cool as they feel',
    avatar: 'lena1_kdgobc',
    avatarHovered: 'lena2_otcylo',
  },
  {
    name: 'Vitalii Ovsiannikov',
    role: 'Frontend Developer',
    photo: 'vitalii',
    contacts: {
      linkedin: 'vitaly-ovsyannikov',
      telegram: 'Degster_oz',
      instagram: 'degster_oz',
    },
    description: 'The one who crafted our website with heart, ensuring every user feels right at home.',
    avatar: 'vitalii1_vy8c8y',
    avatarHovered: 'vitalii2_yuedtl',
  },
  {
    name: 'Elizaveta Bychkova',
    role: 'Backend Engineer',
    photo: 'lisa',
    contacts: {
      instagram: 'lizavettus',
      linkedin: 'lizavettus',
      telegram: 'lizavettus',
    },
    description: 'Always positive, ready to help everyone, creating a seamless atmosphere in the team',
    avatar: 'liza1_bjhk5b',
    avatarHovered: 'liza2_kfzzwg',
  },
  {
    name: 'Ilina Nigmatullina',
    role: 'Product Manager',
    photo: 'ilina',
    contacts: null,
    description: 'Serious and responsible, with her you can trust every detail that builds success.',
    avatar: 'ilina1_iibssv',
    avatarHovered: 'ilina2_gdkqyl',
  },
  {
    name: 'Anastasia Toropova',
    role: 'HR Manager',
    photo: 'anastasia',
    contacts: {
      instagram: 'nastyashtein',
      linkedin: 'nastyatoropova',
      telegram: 'NastyaShtein',
    },
    description: 'The one who keeps the vibes high, always ready with a joke and a shoulder to lean on when things get weird.',
    avatar: 'nastya1_b9gnnp',
    avatarHovered: 'nastya2_qrmtsw',
  },
  {
    name: 'Ekaterina Koroleva',
    role: 'Fullstack QA',
    photo: 'ekaterinaPhoto',
    contacts: {
      linkedin: 'kate-koroleva',
      telegram: 'FennyKat',
    },
    description: 'Finds the cracks before they become problems - and still has time for a laugh about it',
    avatar: 'Katya_laq66l',
    avatarHovered: 'Katya2_xjb9jq',
  },

];
